parameters:
#    vm_meubles.example.class: Vm\MeublesBundle\Example

services:
#    vm_meubles.example:
#        class: %vm_meubles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
